# Generated by Django 2.2 on 2021-08-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll_no', models.IntegerField()),
                ('fee', models.IntegerField()),
                ('grade', models.CharField(max_length=30)),
            ],
        ),
    ]
