# Generated by Django 2.2 on 2021-08-21 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='principalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('qualification', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('appionted_on', models.DateTimeField(default=datetime.datetime(2021, 8, 21, 17, 17, 27, 631016))),
            ],
        ),
    ]
