# Generated by Django 2.2 on 2021-08-21 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalmodel',
            name='appionted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 18, 23, 33, 108022)),
        ),
    ]
