# Generated by Django 2.2 on 2021-08-21 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20210821_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='principalmodel',
            name='appionted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 18, 53, 35, 754069)),
        ),
    ]
