# Generated by Django 2.2 on 2021-08-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='floor_inchargeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
